services:
  - type: web
    name: yuvashankar-portfolio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: EMAIL_USE_TLS
        value: "true"
      - key: EMAIL_USE_SSL
        value: "false"
